name: Storybook
on:
  push:
    branches:
      - main
env:
  NEXT_PUBLIC_A11YWATCH_API: https://api.a11ywatch.com

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Install and Build
        run: |
          yarn --frozen-lockfile
          npm run build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: storybook-static